### PR TITLE
add get-started guide

### PR DESCRIPTION
**Pull request by brightzheng100**

### CODE REVIEW

**Comment by Infra-Red** [comment]
Hi @brightzheng100 ! Thanks for a PR!
From the docs I noticed that Grafana blob is not uploaded to the remote blobstore. I just fixed that in https://github.com/bosh-loki/loki-boshrelease/commit/2f9d0fe2f244edae954a53eb3ca97651bef82933. Could you please remove manual package download step from the docs? Thanks!

**Comment by brightzheng100** [comment]
Since it's been added, the process of course can be simplified.
It's done, @Infra-Red 

Anyway, good job for building this BOSH release.

**Review by Infra-Red — APPROVED** [review]
:shipit:

**Comment by Infra-Red** [comment]
Thanks for the contribution @brightzheng100 !

**Pull request merged**
